#!/usr/bin/env python3
"""
Regenerates the runtime-offset machinery for the external from Offsets.h.

Does two idempotent things:
  1. Converts `inline constexpr uintptr_t X = v;` -> `inline uintptr_t X = v;`
     (mutable so the runtime updater can overwrite values; usage sites are
     unchanged because every access is Offsets::Namespace::Field).
  2. Emits `OffsetsRegistry.h`: a name->&var table keyed as "Namespace::Field",
     matching the keys in https://offsets.imtheo.lol/offsets.json so the
     runtime fetcher can apply fresh values without a rebuild.

Usage:  python3 tools/gen_offsets_registry.py
"""
import os
import re

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OFFSETS = os.path.join(
    REPO,
    "undetected-external-main/UCRobloxExternal/UCRobloxExternal/Src/Game/Offsets/Offsets.h",
)
REGISTRY = os.path.join(
    REPO,
    "undetected-external-main/UCRobloxExternal/UCRobloxExternal/Src/Game/Offsets/OffsetsRegistry.h",
)

FIELD_RE = re.compile(r"^\s*inline\s+(?:constexpr\s+)?uintptr_t\s+(\w+)\s*=\s*")
NS_RE = re.compile(r"^\s*namespace\s+(\w+)\s*\{")
CLOSE_RE = re.compile(r"^\s*\}\s*$")


def main() -> None:
    with open(OFFSETS, "r", encoding="utf-8") as f:
        src = f.read()

    # 1) make every uintptr_t field mutable
    converted = re.sub(
        r"inline\s+constexpr\s+uintptr_t",
        "inline uintptr_t",
        src,
    )

    # 2) walk namespace structure, collecting {ns: [fields]} and their order
    ns_stack = []
    entries = []  # list of (ns, field) in declaration order
    for raw in converted.splitlines():
        m = NS_RE.match(raw)
        if m:
            ns_stack.append(m.group(1))
            continue
        if CLOSE_RE.match(raw):
            if ns_stack:
                ns_stack.pop()
            continue
        fm = FIELD_RE.match(raw)
        if fm and ns_stack and ns_stack[-1] != "Offsets":
            entries.append((ns_stack[-1], fm.group(1)))

    seen = set()
    lines = [
        "#pragma once",
        "// AUTO-GENERATED by tools/gen_offsets_registry.py -- do not edit by hand.",
        "// Maps \"Namespace::Field\" (the keys in offsets.imtheo.lol/offsets.json)",
        "// to the address of the runtime-mutable Offsets variable, so fresh values",
        "// can be applied at startup without a rebuild.",
        "#include \"Offsets.h\"",
        "#include <cstdint>",
        "#include <cstddef>",
        "",
        "namespace Offsets {",
        "    struct OffsetEntry { const char* name; uintptr_t* var; };",
        "    inline const OffsetEntry g_Registry[] = {",
    ]
    for ns, field in entries:
        key = f"{ns}::{field}"
        if key in seen:
            continue
        seen.add(key)
        lines.append(f'        {{ "{key}", &{ns}::{field} }},')
    lines += [
        "    };",
        "    inline const size_t g_RegistryCount = sizeof(g_Registry) / sizeof(g_Registry[0]);",
        "}",
        "",
    ]

    if src != converted:
        with open(OFFSETS, "w", encoding="utf-8") as f:
            f.write(converted)
        print(f"[gen] Offsets.h: made {converted.count('inline uintptr_t') - src.count('inline uintptr_t')} fields mutable")
    else:
        print("[gen] Offsets.h: already mutable (no change)")

    with open(REGISTRY, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"[gen] OffsetsRegistry.h: wrote {len(seen)} entries")


if __name__ == "__main__":
    main()
